# Site Info
title: Jerry's Git Blog
tagline: 'for vision'
description: 'blog for textmining'
url: http://kkkjerry.github.io
logo:
encoding: utf-8

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty
version: 1.0.0

# About/contact
author:
  name: Jerry
  description:
  gravatar: https://github.com/kkkjerry/kkkjerry.github.io/tree/master/public/img/IMG_2918.JPG
  contact:
    #linkedin:  https://www.linkedin.com/in/gichanglee/
    github:    https://github.com/kkkjerry
    facebook:  https://www.facebook.com/jerry.kim.566
    #twitter:  <hide>
    #weibo:    <hide>
    email:     mailto:jaeyeol2931@gc.gachon.ac.kr

# Navigation (2nd level links supported)
nav:
  Home:
    - '/'
  Contents:
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:
    - '/about/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: https://kkkjerry.github.io/public/img/cat.JPG
  caption: I'm jerry. I love cat.

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-93172815-1' # leave blank if you don't want google analytics
disqus_short_name: 'kkkjerry-github-io' # leave blank if you don't want disqus
